export default {
    tintColor: '#80C241',
    background: '#F6F6F6',
    primaryColor: '#7CB342',
    white: '#FFF',
    black: '#000',
    divider: '#dedede',
    lightGray: '#EEEEEE',
    darkGray: '#AAAAAA',
    textSubTitle: '#9B9B9B',
    tabIconDefault: '#888',
    tabIconSelected: '#80C241',
    tabBar: '#FEFEFE',
    text: 'rgb(117, 120, 123)',
    textSecondary: '#999',
    errorBackground: 'red',
    errorText: '#FFF',
    warningBackground: '#EAEB5E',
    warningText: '#666804',
    noticeBackground: '#4BB543',
    noticeText: '#fff',
    red: '#e83f6f',
    nice_blue: '#198aaf',
    transparent: 'rgba(0,0,0,0)',
    itemDivider: '#f7f7f7',
    checkBoxUnchecked: '#818181',
}
